name: Build VPM Listing

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-listing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: vrchat-community/package-list-action@0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
